#!/bin/bash
rm //n000325/home/_namatv/xz/*.git.tar.xz
cd //n000325/home/_namatv/_git
for i in `find . -name "*.git"`
do

    BNAME=`basename $i`
    echo $i
    echo $BNAME
    tar -cvvJf $BNAME.tar.xz $BNAME/
    mv $BNAME.tar.xz //n000325/home/_namatv/xz/
done
