#!/bin/bash
LOCATION_XZ="/home/namatv/xz"
LOCATION_GIT="/home/namatv/git"

rm -f $LOCATION_XZ/*.git.tar.xz
mkdir -p $LOCATION_XZ
cd $LOCATION_GIT
for i in `find . -name "*.git"`
do
    BNAME=`basename $i`
    echo $i
    echo $BNAME
    tar -cvvJf $BNAME.tar.xz $BNAME/
    mv $BNAME.tar.xz $LOCATION_XZ/
done
