#!/bin/bash
#
# Выполняет перенос на сайт pi пакетов и файлов синхронизации,
# необходимях для обновления msys2.

. clp-config

clp-check-public

if [[ -d "${VAR_CACHE_PACMAN}" && -d "${VAR_CACHE_PACMAN}" ]]
then
    cd ${VAR_CACHE_PACMAN}
    tar -cvvJf pkg.tar.xz pkg/
    mv pkg.tar.xz "${PUB_HTML_CLP_ARH}/"

    cd ${VAR_LIB_PACMAN}
    tar -cvvJf sync.tar.xz sync/
    mv sync.tar.xz "${PUB_HTML_CLP_ARH}/"

    clp-dot-emacs-d-public
    
    clp-quicklisp-public

    clp-xz-public

    rs-local-pi
fi
