#!/bin/bash
#
#  Выполняет перенос в каталог public файлов, необходимях для обновления quicklisp.

clp-check-public
####################
# ~/quicklisp/dists
####################    
cd ~/quicklisp/dists
tar -cvvJf quicklisp.tar.xz ./quicklisp/*.cdb ./quicklisp/*.txt ./quicklisp/archives/
mv quicklisp.tar.xz ~/public_html/Common-Lisp-Programs/Archive/


