#!/bin/bash
#
# Выполняет перенос на сайт pi пакетов и файлов синхронизации,
# необходимях для обновления msys2.

mkdir -p ~/public_html/Common-Lisp-Programs/Archive

VAR_CACHE_PACMAN="/var/cache/pacman"
VAR_LIB_PACMAN="/var/lib/pacman"

if [[ -d "$VAR_CACHE_PACMAN" && -d "$VAR_CACHE_PACMAN" ]]
then
    cd ${VAR_CACHE_PACMAN}
    tar -cvvJf pkg.tar.xz pkg/
    mv pkg.tar.xz ~/public_html/Common-Lisp-Programs/Archive/

    cd ${VAR_LIB_PACMAN}
    tar -cvvJf sync.tar.xz sync/
    mv sync.tar.xz ~/public_html/Common-Lisp-Programs/Archive/
    ####################
    # dot.emacs.d.tar.xz
    ####################    
    cd ~
    tar -cvvJf dot.emacs.d.tar.xz .emacs.d/
    mv dot.emacs.d.tar.xz ~/public_html/Common-Lisp-Programs/Archive/
    ####################
    # ~/quicklisp/dists
    ####################    
    cd ~/quicklisp/dists
    tar -cvvJf quicklisp.tar.xz ./quicklisp/*.cdb ./quicklisp/*.txt ./quicklisp/archives/
    mv quicklisp.tar.xz ~/public_html/Common-Lisp-Programs/Archive/
#    ####################
#    # git-tree.git
#    ####################
#    cd ~/public_html/Common-Lisp-Programs/Archive/
#    git clone --bare git@pi:/opt/git/git-tree.git
#    tar -cvvJf git-tree.git.tar.xz git-tree.git/
#    rm -rf git-tree.git
#    mv git-tree.git.tar.xz ~/public_html/Common-Lisp-Programs/Archive/
    ####################
    # xz.tar
    ####################
    clp-local-remake-git
    clp-local-remake-xz
    cd ~/xz
    tar -cvvf xz.tar *.git.tar.xz
    mv xz.tar ~/public_html/Common-Lisp-Programs/Archive/
    ####################
    clp-local-pi
fi
