#!/bin/bash

clp-config

mkdir -p "$REPO_URL_PP"
cd "$REPO_URL_PP"
if [[ `pwd` == "$REPO_URL_PP" ]]
then
    rm -rf *.git
fi
for i in `ls ${REPO_XZ_PP}/*.git.tar.xz`
do tar -xvf $i
done

mkdir -p "$REPO_URL_PZ"
cd "$REPO_URL_PZ"
if [[ `pwd` == "$REPO_URL_PZ" ]]
then
    rm -rf *.git
fi
for i in `ls ${REPO_XZ_PZ}/*.git.tar.xz`
do tar -xvf $i
done
