#!/bin/bash
#
# Выполняет перенос в каталог ~/public_html/Common-Lisp-Programs/Archive/ архивов git.tar.xz 

clp-check-public
####################
# xz.tar
####################
remake-git
remake-xz
cd ~/xz
tar -cvvf xz.tar *.git.tar.xz
mv xz.tar ~/public_html/Common-Lisp-Programs/Archive/
