#!/bin/bash
#
# Выполняет перенос на сайт pi пакетов и файлов синхронизации,
# необходимях для обновления msys2.

clp-check-public
####################
# dot.emacs.d.tar.xz
####################    
cd ~
tar -cvvJf dot.emacs.d.tar.xz .emacs.d/
mv dot.emacs.d.tar.xz ~/public_html/Common-Lisp-Programs/Archive/

