#!/bin/bash
# Создает архивы git.tar.xz для мест расположения чистых репозиториев pp и pz

. clp-config 

rm -f $REPO_XZ_PP/*.git.tar.xz
mkdir -p $REPO_XZ_PP
cd $REPO_URL_PP
for i in `find . -name "*.git"`
do
    BNAME=`basename $i`
    echo $i
    echo $BNAME
    tar -cvvJf $BNAME.tar.xz $BNAME/
    mv $BNAME.tar.xz $REPO_XZ_PP/
done

rm -f $REPO_XZ_PZ/*.git.tar.xz
mkdir -p $REPO_XZ_PZ
cd $REPO_URL_PZ
for i in `find . -name "*.git"`
do
    BNAME=`basename $i`
    echo $i
    echo $BNAME
    tar -cvvJf $BNAME.tar.xz $BNAME/
    mv $BNAME.tar.xz $REPO_XZ_PZ/
done
