#!/bin/bash
#
# Выполняет перенос на сайт pi пакетов и файлов синхронизации,
# необходимях для обновления msys2.

clp-check-public

VAR_CACHE_PACMAN="/var/cache/pacman"
VAR_LIB_PACMAN="/var/lib/pacman"

if [[ -d "$VAR_CACHE_PACMAN" && -d "$VAR_CACHE_PACMAN" ]]
then
    cd ${VAR_CACHE_PACMAN}
    tar -cvvJf pkg.tar.xz pkg/
    mv pkg.tar.xz ~/public_html/Common-Lisp-Programs/Archive/

    cd ${VAR_LIB_PACMAN}
    tar -cvvJf sync.tar.xz sync/
    mv sync.tar.xz ~/public_html/Common-Lisp-Programs/Archive/

    clp-dot-emacs-d-public
    
    clp-quicklisp-public

    clp-xz-public

    clp-local-pi
fi
