#!/bin/bash
#
REPO_NAME_PP="pp"
REPO_NAME_PZ="pz"
REPO_NAME_PI="pi"
REPO_NAME_ORIGIN="origin"
#
REPO_URL_GIT_PP="$HOME/git"
REPO_URL_GIT_PZ="$HOME/git-big"
REPO_URL_GIT_PI="git@mnasoft.ddns.mksat.net:/opt/git"
REPO_URL_GIT_ORIGIN="//n000325/home/_namatv/_git"
#
REPO_URL_XZ_PP="$HOME/xz"
REPO_URL_XZ_PZ="$HOME/xz-big"
#
REPO_XZ_TAR_PP="xz.tar"
#
PUB_HTML_CLP_ARH="~/public_html/Common-Lisp-Programs/Archive"
#
VAR_CACHE_PACMAN="/var/cache/pacman"
VAR_LIB_PACMAN="/var/lib/pacman"

func_git_tree_echo_short ()
{
#    echo '--------------------' 
}

func_git_tree_echo_long ()
{
    echo '---------------------------------' 
}

func_git_tree_echo_long_plus ()
{
    echo '+++++++++++++++++++++++++++++++++' 
}

func_git_tree_echo_long_equal ()
{
    echo '================================='
}
####################################################################################################
#### func_clp_check_public
####################################################################################################

func_clp_check_public ()
{
    mkdir -p "${PUB_HTML_CLP_ARH}"
}

####################################################################################################
#### For remake-git-pp
####################################################################################################

func_remove_git_pp ()
{
    rm -rf $REPO_URL_GIT_PP/*.git
}

func_remove_git_pz ()
{
    rm -rf $REPO_URL_GIT_PZ/*.git
}

func_remake_git_pp ()
{
    CDIR=`pwd`
    for i in `find . -name "*.git"`
    do
        cd $i/..
        if [[ `git remote | grep pp` ]]
        then
            NAME=`pwd`
            BNAME=`basename $NAME`
            echo $i
            echo $NAME
            echo $BNAME
            cd ..
            git clone --bare $BNAME $REPO_URL_GIT_PP/$BNAME.git
        else
            cd ..
        fi
        cd $CDIR
    done
}

func_remake_git_pz ()
{
    CDIR=`pwd`
    for i in `find . -name "*.git"`
    do
        cd $i/..
        if [[ `git remote | grep pz` ]]
        then
            NAME=`pwd`
            BNAME=`basename $NAME`
            echo $i
            echo $NAME
            echo $BNAME
            cd ..
            git clone --bare $BNAME $REPO_URL_GIT_PZ/$BNAME.git
        else
            cd ..
        fi
        cd $CDIR
    done
}

####################################################################################################
#### func_remake_git_pp_all
####################################################################################################

func_remake_git_pp_all ()
{
    func_remove_git_pp
    
    cd ~/quicklisp/local-projects/
    func_remake_git_pp

    cd ~/develop/
    func_remake_git_pp

    cd ~/elisp/
    func_remake_git_pp
}

####################################################################################################
#### remake-xz-pp
####################################################################################################

func_remake_xz_pp_all ()
{
    func_remove_repo_xz_pp
    func_remake_xz_pp
}

####################################################################################################
#### remake_xz_pz
####################################################################################################

func_remake_xz_pz_all ()
{
    func_remove_repo_xz_pz
    func_remake_xz_pz
}

####################################################################################################
# clp-xz-public func_clp_xz_public
####################################################################################################

func_clp_xz_public ()
{
    func_remake_git_pp_all
    func_remake_xz_pp_all
    cd ${REPO_URL_XZ_PP}
    tar -cvvf ${REPO_XZ_TAR_PP} *.git.tar.xz
    mv ${REPO_XZ_TAR_PP} "${PUB_HTML_CLP_ARH}/"
}

####################################################################################################
#### remake-xz-pp
####################################################################################################

func_remove_repo_xz_pp ()
{
    rm -f $REPO_URL_XZ_PP/*.git.tar.xz
}

func_remake_xz_pp ()
{
    mkdir -p $REPO_URL_XZ_PP
    cd $REPO_URL_GIT_PP
    for i in `find . -name "*.git"`
    do
        BNAME=`basename $i`
        echo $i
        echo $BNAME
        tar -cvvJf $BNAME.tar.xz $BNAME/
        mv $BNAME.tar.xz $REPO_URL_XZ_PP/
    done
}

func_remove_repo_xz_pz ()
{
    rm -f $REPO_URL_XZ_PZ/*.git.tar.xz
}

func_remake_xz_pz ()
{
    mkdir -p $REPO_URL_XZ_PZ
    cd $REPO_URL_GIT_PZ
    for i in `find . -name "*.git"`
    do
        BNAME=`basename $i`
        echo $i
        echo $BNAME
        tar -cvvJf $BNAME.tar.xz $BNAME/
        mv $BNAME.tar.xz $REPO_URL_XZ_PZ/
    done
}

####################################################################################################
#### git_tree
####################################################################################################

GIT_TREE_USAGE="
Usage: $(basename $0) COMMAND [BRANCH]

Command: 
        pull          - получение изменений с сервера;
        push          - отправка изменений на сервер;
        pullsh        - получение и отправка изменений;
        add           - добавление изменений;
        commit        - фиксация изменений;
        all           - получение изменений с сервера, добавление изменений,
                        фиксация изменений, отправка изменений на сервер;
        readd_pp      - удаление и повторное добавление удаленного
                        репозитория pp;
        readd_pz      - удаление и повторное добавление удаленного
                        репозитория pz;
        readd_pi      - удаление и повторное добавление удаленного
                        репозитория pi;
        readd_origin  - удаление и повторное добавление удаленного
                        репозитория origin;
        rm_pp         - удаление удаленного репозитория pp;
        rm_pz         - удаление удаленного репозитория pz;
        rm_pi         - удаление удаленного репозитория pi;
        rm_origin     - удаление удаленного репозитория origin;

        clone_bare_pp - клонирование дерева репозиториев в
                        расположение pp;
        clone_bare_pz - клонирование дерева репозиториев в
                        расположение pz;
        clone_bare_pi - клонирование дерева репозиториев в
                        расположение pi;
        clone_bare_or - клонирование дерева репозиториев в
                        расположение origin;

Описание:

         Выполняет поиск репозиториев git, начиная с текущего
         каталога. Для каздого из, найденных репозиториев выполняет
         команду COMMAND для всех удаленных репозиториев.

         Необязательный параметр BRANCH задает ветку,
         получаемую|отправляемую на удаленные сервера. Если он не
         задан синхронизируется текущая ветка.
"

func_git_tree_usage_show ()
{
    echo "${GIT_TREE_USAGE}"
}

func_git_tree_push ()
{
    for rpo in `git remote`
    do
        func_git_tree_echo_short
        echo ">>> git push ${rpo} ${DO_BRANCH} <<<"
        git push ${rpo} ${DO_BRANCH}
        func_git_tree_echo_short
    done
}

func_git_tree_pull ()
{
    for rpo in `git remote`
    do
        func_git_tree_echo_short
        echo ">>> git pull ${rpo} ${DO_BRANCH} <<<"
        git pull ${rpo} ${DO_BRANCH}
        func_git_tree_echo_short
    done
}

func_git_tree_add ()
{
    func_git_tree_echo_short
    echo '>>> git add `find . -name "*.lisp" -o -name "*.org" -o -name "*.asd"` <<<'
    git add `find . -name "*.lisp" -o -name "*.org" -o -name "*.asd"`
# -o -name "*.scr" 
    
    func_git_tree_echo_short
}

func_git_tree_readd_pp ()
{
    func_git_tree_echo_short
    echo ">>> git remote remove ${REPO_NAME_PP} <<<"
    git remote remove ${REPO_NAME_PP}
    DIR_REPO=`pwd`
    REPO=`basename ${DIR_REPO}`
    echo ">>> git remote add ${REPO_NAME_PP} ${REPO_URL_GIT_PP}/${REPO}.git <<<"
    git remote add ${REPO_NAME_PP} ${REPO_URL_GIT_PP}/${REPO}.git
    func_git_tree_echo_short
}

func_git_tree_readd_pz ()
{
    func_git_tree_echo_short
    echo ">>> git remote remove ${REPO_NAME_PZ} <<<"
    git remote remove ${REPO_NAME_PZ}
    DIR_REPO=`pwd`
    REPO=`basename ${DIR_REPO}`
    echo ">>> git remote add ${REPO_NAME_PZ} ${REPO_URL_GIT_PZ}/${REPO}.git <<<"
    git remote add ${REPO_NAME_PZ} ${REPO_URL_GIT_PZ}/${REPO}.git
    func_git_tree_echo_short
}

func_git_tree_readd_pi ()
{
    func_git_tree_echo_short
    echo ">>> git remote remove ${REPO_NAME_PI} <<<"
    git remote remove ${REPO_NAME_PI}
    DIR_REPO=`pwd`
    REPO=`basename ${DIR_REPO}`
    echo ">>> git remote add ${REPO_NAME_PI} ${REPO_URL_GIT_PI}/${REPO}.git <<<"
    git remote add ${REPO_NAME_PI} ${REPO_URL_GIT_PI}/${REPO}.git
    func_git_tree_echo_short
}

func_git_tree_readd_origin ()
{
    func_git_tree_echo_short
    echo ">>> git remote remove ${REPO_NAME_ORIGIN} <<<"
    git remote remove ${REPO_NAME_ORIGIN}
    DIR_REPO=`pwd`
    REPO=`basename ${DIR_REPO}`
    echo ">>> git remote add ${REPO_NAME_ORIGIN} ${REPO_URL_GIT_ORIGIN}/${REPO}.git <<<"
    git remote add ${REPO_NAME_ORIGIN} ${REPO_URL_GIT_ORIGIN}/${REPO}.git
    func_git_tree_echo_short
}

func_git_rm_pp ()
{
    func_git_tree_echo_short
    echo ">>> git remote remove ${REPO_NAME_PP} <<<"
    git remote remove ${REPO_NAME_PP}
    func_git_tree_echo_short
}

func_git_rm_pz ()
{
    func_git_tree_echo_short
    echo ">>> git remote remove ${REPO_NAME_PZ} <<<"
    git remote remove ${REPO_NAME_PZ}
    func_git_tree_echo_short
}

func_git_rm_pi ()
{
    func_git_tree_echo_short
    echo ">>> git remote remove ${REPO_NAME_PI} <<<"
    git remote remove ${REPO_NAME_PI}
    func_git_tree_echo_short
}

func_git_rm_origin ()
{
    func_git_tree_echo_short
    echo ">>> git remote remove ${REPO_NAME_ORIGIN} <<<"
    git remote remove ${REPO_NAME_ORIGIN}
    func_git_tree_echo_short
}

func_git_clone_bare_pp ()
{
    BASENAME=`pwd`
    DIR_NAME=`basename ${BASENAME}`
    func_git_tree_echo_short
    echo ">>> git clone --bare . ${REPO_URL_GIT_PP}/${DIR_NAME}.git <<<"
    git clone --bare . ${REPO_URL_GIT_PP}/${DIR_NAME}.git
    func_git_tree_echo_short
}

func_git_clone_bare_pz ()
{
    BASENAME=`pwd`
    DIR_NAME=`basename ${BASENAME}`
    func_git_tree_echo_short
    echo ">>> git clone --bare . ${REPO_URL_GIT_PZ}/${DIR_NAME}.git <<<"
    git clone --bare . ${REPO_URL_GIT_PZ}/${DIR_NAME}.git
    func_git_tree_echo_short
}

func_git_clone_bare_pi ()
{
    BASENAME=`pwd`
    DIR_NAME=`basename ${BASENAME}`
    func_git_tree_echo_short
    echo ">>> git clone --bare . ${REPO_URL_GIT_PI}/${DIR_NAME}.git <<<"
    git clone --bare . ${REPO_URL_GIT_PI}/${DIR_NAME}.git
    func_git_tree_echo_short
}

func_git_clone_bare_origin ()
{
    BASENAME=`pwd`
    DIR_NAME=`basename ${BASENAME}`
    func_git_tree_echo_short
    echo ">>> git clone --bare . ${REPO_URL_GIT_ORIGIN}/${DIR_NAME}.git <<<"
    git clone --bare . ${REPO_URL_GIT_ORIGIN}/${DIR_NAME}.git
    func_git_tree_echo_short
}

func_git_tree_commit ()
{
    func_git_tree_echo_short
    echo '>>> git commit -a -m "`date -u`" <<<'
    git commit -a -m "`date -u`"
    func_git_tree_echo_short
}

func_git_tree_push_or_pull ()
{
    for rpo in `git remote`
    do
    func_git_tree_echo_short
    echo ">>> git ${COMMAND} ${rpo} ${DO_BRANCH} <<<"
    git ${COMMAND} ${rpo} ${DO_BRANCH}
    func_git_tree_echo_short
    done
}

func_git_tree_command_branch ()
{
    CURRENT_BRANCH=`git branch --no-color | grep \*  | cut -d ' ' -f 2`
    if ! [[ -z "${BRANCH}" ]]
    then
        DO_BRANCH="${BRANCH}"
    else
        DO_BRANCH="${CURRENT_BRANCH}"
    fi
# pull          - получение изменений с сервера;
# push          - отправка изменений на сервер;
    if [[ ${COMMAND} == "push" || ${COMMAND} == "pull" ]]
    then
        func_git_tree_push_or_pull
    fi
# pullsh        - получение и отправка изменений;    
    if [[ ${COMMAND} == "pullsh" ]]
    then
        func_git_tree_pull
        func_git_tree_push
    fi
# add - добавление изменений;    
    if [[ ${COMMAND} == "add" ]]
    then
        func_git_tree_add
    fi
# commit        - фиксация изменений;    
    if [[ ${COMMAND} == "commit" ]]
    then
        func_git_tree_commit
    fi
# all           - получение изменений с сервера, добавление изменений,
#                 фиксация изменений, отправка изменений на сервер;
    if [[ ${COMMAND} == "all" ]]
    then
        func_git_tree_pull
        func_git_tree_add
        func_git_tree_commit
        func_git_tree_push
    fi
# readd_pp      - удаление и повторное добавление удаленного
#                 репозитория pp;
    if [[ ${COMMAND} == "readd_pp" ]]
    then
        func_git_tree_readd_pp
    fi
# readd_pz      - удаление и повторное добавление удаленного
#                 репозитория pz;
    if [[ ${COMMAND} == "readd_pz" ]]
    then
        func_git_tree_readd_pz
    fi
# readd_pi      - удаление и повторное добавление удаленного
#                 репозитория pi;
    if [[ ${COMMAND} == "readd_pi" ]]
    then
        func_git_tree_readd_pi
    fi
# readd_origin  - удаление и повторное добавление удаленного
#                 репозитория origin;
    if [[ ${COMMAND} == "readd_origin" ]]
    then
        func_git_tree_readd_origin
    fi
# rm_pp         - удаление удаленного репозитория pp;
    if [[ ${COMMAND} == "rm_pp" ]]
    then
        func_git_rm_pp
    fi
# rm_pz         - удаление удаленного репозитория pz;
    if [[ ${COMMAND} == "rm_pz" ]]
    then
        func_git_rm_pp
    fi
# rm_pi         - удаление удаленного репозитория pi;    
if [[ ${COMMAND} == "rm_pi" ]]
    then
        func_git_rm_pp
    fi    
# rm_origin     - удаление удаленного репозитория origin;
    if [[ ${COMMAND} == "rm_origin" ]]
    then
        func_git_rm_origin
    fi
# clone_bare_pp - клонирование дерева репозиториев в расположение pp;    
    if [[ ${COMMAND} == "clone_bare_pp" ]]
    then
        func_git_clone_bare_pp
    fi
# clone_bare_pz - клонирование дерева репозиториев в расположение pz;    
    if [[ ${COMMAND} == "clone_bare_pz" ]]
    then
        func_git_clone_bare_pz
    fi
# clone_bare_pi - клонирование дерева репозиториев в расположение pi;     
    if [[ ${COMMAND} == "clone_bare_pi" ]]
    then
        func_git_clone_bare_pp
    fi
# clone_bare_or - клонирование дерева репозиториев в расположение origin;    
    if [[ ${COMMAND} == "clone_bare_or" ]]
    then
        func_git_clone_bare_origin
    fi
}

func_git_tree_command ()
{
    CDIR=`pwd`
    for i in `find . -name ".git"`
    do
        func_git_tree_echo_long_equal
        cd ${CDIR}/${i}/../
        echo "`pwd`"
        func_git_tree_echo_long
        func_git_tree_command_branch
        func_git_tree_echo_long_plus
    done
    cd ${CDIR}
}

func_git_tree ()
{
    if ! [[ -z "$2" ]]
    then
        BRANCH=$2
        echo ${BRANCH}
    fi

    if [ -z "$1" ]
    then
        func_git_tree_usage_show
    else
        COMMAND=$1
        if [[ ${COMMAND} == "push"          || \
                  ${COMMAND} == "pull"          || \
                  ${COMMAND} == "pullsh"        || \
                  ${COMMAND} == "add"           || \
                  ${COMMAND} == "commit"        || \
                  ${COMMAND} == "all"           || \
                  ${COMMAND} == "readd_pp"      || \
                  ${COMMAND} == "readd_pz"      || \
                  ${COMMAND} == "readd_pi"      || \
                  ${COMMAND} == "readd_origin"  || \
                  ${COMMAND} == "rm_pp"         || \
                  ${COMMAND} == "rm_pz"         || \
                  ${COMMAND} == "rm_pi"         || \
                  ${COMMAND} == "rm_origin"     || \
                  ${COMMAND} == "clone_bare_pp" || \
                  ${COMMAND} == "clone_bare_pz" || \
                  ${COMMAND} == "clone_bare_pi" || \
                  ${COMMAND} == "clone_bare_or" ]]
        then
            func_git_tree_command
        else
            echo "Unknown command: ${COMMAND}"
            func_git_tree_usage_show
        fi
    fi
}

####################################################################################################
#### 
####################################################################################################
