#!/bin/bash

. /etc/git-tree/git-tree.conf

CDIR=`pwd`
BNAME=`basename $CDIR`

git remote remove n142013-pp
git remote remove n142013-pz

if [[ `git remote | grep pp` -eq "pp" ]]
then
    git remote add n142013-pp //n142013/home/_namatv/PRG/msys64/home/namatv/.git-tree/git/pp/${BNAME}.git
fi   

if [[ `git remote | grep pz` -eq "pz" ]]
then
    git remote add n142013-pz //n142013/home/_namatv/PRG/msys64/home/namatv/.git-tree/git/pz/${BNAME}.git
fi   

