#!/bin/bash

. /etc/git-tree/git-tree.conf

GIT_TREE_DOWNLOAD_USAGE="
NAME
        $(basename $0) выполняет однотипные операции над репозиториями
                 git, расположенными в дереве каталогов.

SYNOPSIS
        $(basename $0) dir
"

show_usage ()
{
    echo "${GIT_TREE_DOWNLOAD_USAGE}"
}


main ()
{
# Проверка переметров начало
    if [ -z "$1" ]
    then
        show_usage
        exit 1
    else
        DIR_TAR=$1
        if [ -f ${DIR_TAR}/${TAR_pp} ]
        then
            cd ${URL_XZ_pp}
            cp ${DIR_TAR}/${TAR_pp} .
            tar -xvf ${TAR_pp}
            git tree xz_git pp
        else
            echo "Укажите каталог, в котором расположен файл с именем ${TAR_pp}"
        fi
        
        if [ -f ${DIR_TAR}/${TAR_pz} ]
        then
            cd ${URL_XZ_pz}
            cp ${DIR_TAR}/${TAR_pz} .
            tar -xvf ${TAR_pz}
            git tree xz_git pz
        else
            echo "Укажите каталог, в котором расположен файл с именем ${TAR_pz}"
        fi        
    fi

    for i in ${TREE_PATH}
    do
        cd $i; git tree pull
    done
}   

# cd ${URL_XZ_pp}
# cp ${DIR_TAR}/${TAR_pp} .
# tar -xvf ${TAR_pp}
# git tree xz_git pp

# cd ${URL_XZ_pz}
# cp ${DIR_TAR}/${TAR_pz} .
# tar -xvf ${TAR_pz}
# git tree xz_git pz

# for i in ${TREE_PATH}
# do
#    cd $i; git tree pull
# done

main "$@"            
