#!/bin/bash

REPO="pi"
REMOTE_GIT_SERVER="git@pi:/opt/git"

CDIR=`pwd`

REPO_PI=`git remote | grep pi`

if [[ ${REPO_PI} ==  ${REPO} ]]
then
    B_NAME=`basename $CDIR`
    echo $B_NAME
    cd ../
    rm -rf $B_NAME
    git clone $REMOTE_GIT_SERVER/$B_NAME.git
    cd $B_NAME
    git remote rename origin ${REPO}
fi

# CDIR_00==`pwd`
# for i in `find . -name ".git"`
# do
#     cd ${CDIR_00}/${i}/..
#     git-reclone
# done
