#!/bin/bash

hostname_readd ()
{
    if [[ "N142013" == `hostname` ]]
    then
        echo "git tree readd pb"
        git tree readd pb
    fi
}
cd ~/devel/git-tree
hostname_readd
git tree all
sh ./INSTALL.run

cd ~/quicklisp/local-projects/ZM/cfx/n70-base
hostname_readd
git tree all

cd ~/quicklisp/local-projects/ANSYS/mnas-ansys
hostname_readd
git tree all

cd ~/quicklisp/local-projects/clisp/math
hostname_readd
git tree all

cd ~/quicklisp/local-projects/mnas/mnas-string
hostname_readd
git tree all

