#!/bin/bash

REPO="pi"
REMOTE_GIT_SERVER="git@pi:/opt/git"

CDIR=`pwd`
B_NAME=`basename $CDIR`
echo $B_NAME
cd ../
rm -rf $B_NAME
git clone $REMOTE_GIT_SERVER/$B_NAME.git
cd $B_NAME
git remote rename origin ${REPO}
