#!/bin/bash

echo "" > INSTALL.log
echo "" > UNINSTALL.run

mkdir -p /usr/local/bin/
git clean -fx
for i in `find . -name "git-*" -o -name "clp-*" -o -name "rs-*" -o -name "slynk-*" -o -name "pi-*" -o -name "remake-*" -o -name "xz-*"`
do
    echo "${i}"
    cp -f ${i} /usr/local/bin/
    chmod +x /usr/local/bin/${i}
    echo "/usr/local/bin/${i}" >> INSTALL.log
    echo "rm -f /usr/local/bin/${i}" >> UNINSTALL.run
    chmod +x UNINSTALL.run
done
