
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: README
#+date: <2021-05-02 Вс>
#+author:
#+email: mnasoft@gmail.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.2 (Org mode 9.4.4)
#+options: html-link-use-abs-url:nil html-postamble:auto
#+options: html-preamble:t html-scripts:t html-style:t
#+options: html5-fancy:nil tex:t
#+html_doctype: xhtml-strict
#+html_container: div
#+description:
#+keywords:
#+html_link_home:
#+html_link_up:
#+html_mathjax:
#+html_equation_reference_format: \eqref{%s}
#+html_head:
#+html_head_extra:
#+subtitle:
#+infojs_opt:
#+creator: <a href="https://www.gnu.org/software/emacs/">Emacs</a> 27.2 (<a href="https://orgmode.org">Org</a> mode 9.4.4)
#+latex_header:

* Назначение
 Пакет предназначен для выполнения однотипных операций на дереве
 каталогов, содержащем репозитории git.
* Установка
#+begin_src shell
   sudo ./INSTALL.run
#+end_src
* Удаление
#+begin_src shell
   sudo ./UNINSTALL.run 
#+end_src

clp-config            - системные переменные
git-tree              - работа с деревом репозиториев
git-reclone           - удаление каталога, содержащего репозиторий pi и повторное его клонирование из удаленного репозитория
clp-check-public      - создает на каталог ~/public_html/Common-Lisp-Programs/Archive

clp-dot-emacs-d-pi
clp-dot-emacs-d-public
remake-git           - Выполняет пересоздание каталога ~/git, наполняя его чистыми репозиториями. Поиск репозиротиев ведется в каталогах: ~/quicklisp/local-projects/; ~/develop/; ~/elisp/.
remake-xz            - Создает архивы git.tar.xz для мест расположения чистых репозиториев pp и pz
xz-git               - Распаковывает архивы git.tar.xz, содержащие репозитории git, в каталоги с чистыми репозиториями для pp и pz расположений.
clp-pacman-Suy       - Выполняет перенос на сайт pi пакетов и файлов синхронизации, необходимях для обновления msys2.
clp-quicklisp-pi     - Выполняет перенос на сайт pi файлов, необходимях для обновления quicklisp.
clp-quicklisp-public - Выполняет перенос в каталог public файлов, необходимях для обновления quicklisp.
clp-xz-pi            - Выполняет перенос на сайт pi ~/public_html/Common-Lisp-Programs/Archive/ архивов git.tar.xz.
clp-xz-public        - Выполняет перенос в каталог ~/public_html/Common-Lisp-Programs/Archive/ архивов git.tar.xz.

git-tree-repo
git-tree-temp - Содержит фрагменты кода

rs-local-pi - Синхронизация папки ~/public_html/ с с сервером mnasoft.ddns.mksat.net.
rs-pi-html  - Синхронизация папки ~/public_html/Common-Lisp-Programs/ с сервером mnasoft.ddns.mksat.net
rs-pi-local - Синхронизация mnasoft.ddns.mksat.net с папкой ~/public_html.

README.org - настоящий документ
ToDo.org 
INSTALL.log - лог установки
INSTALL.run - сценарий установки
UNINSTALL.run - сценарий удаления



* Команды
  1. Установка / Удаление
     + INSTALL.run - содержит команды установки комплекса скриптов в
       системе;
     + UNINSTALL.run - содержит команды деинталляции комплекса скриптов в
       системе;
     + INSTALL.log - содержит перечень файлов, установленных
       комплексом шрифтов в системе;
  2. Выполнение операций git на дереве коталогов
     + git-tree-repo - выполняет команду для каждого репозитория git,
       найденного в дереве каталогов, для конкретного удаленного
       репозитория.
     + git-tree - выполняет команду для каждого репозитория git,
       найденного в дереве каталогов, для всех удаленных репозиторев.
  3. Повторное клонированние с удалением
     + git-reclone - для каталога, содержащего git-репозиторий
       выполняет:
       - проверку того, что в git-репозитории существует ссылка на
         удаленный git-репозиторий;
       - в случае успеха переходит вышележащий каталог, удаляет
         git-репозиторий и затем осуществляет попытку его повторного
         клонирования.
  4. PI
     + rs-local-pi - выполняет синхронизацию папки
       ~/public_html/Common-Lisp-Programs с удаленным компьютером pi.
     + rs-pi-local - выполняет синхронизацию удаленного компьютера pi
       с папкой ~/public_html/Common-Lisp-Programs
  5. n000325
     + clp-n000325-remake-git
     + clp-n000325-remake-xz
  6. clp-check-public - создает на каталог
     ~/public_html/Common-Lisp-Programs/Archive

* Примеры использования
1. Перейдите в каталог, в котором содержатся репозитории git.
2. Выполните команду
#+begin_src shell
 git-tree
#+end_src
