#!/bin/bash

# Выполняет пересоздание каталога ~/git, наполняя его чистыми
# репозиториями. Поиск репозиротиев ведется в каталогах:
# ~/quicklisp/local-projects/; ~/develop/; ~/elisp/.

. clp-config 

func_remove_git_pp

cd ~/quicklisp/local-projects/
func_remake_git_pp

cd ~/develop/
func_remake_git_pp

cd ~/elisp/
func_remake_git_pp
