#!/bin/bash
#
# Выполняет перенос на сайт pi пакетов и файлов синхронизации,
# необходимях для обновления msys2.

. clp-config

func_rs_pacman

#    clp-dot-emacs-d-public
    
#    clp-quicklisp-public

#    clp-xz-public

#    rs-local-pi

